num1 = rbind(rep(1,3), rep(2,3), rep(3,3))
print("num1")
print(num1)
num2 = rbind(rep(4,3), rep(5,3), rep(6,3))
print("num2")
print(num2)
num3 = rbind(rep(7,3), rep(8,3), rep(9,3))
print("num3")
print(num3)
a = matrix(t(cbind(num1,num2,num3)),ncol=3, byrow=T)
print("Combine three arrays, taking one row from each one by one:")
print(a)
